name: Deploy Serverless Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Verify AWS Credentials
      run: aws sts get-caller-identity

    - name: Install dependencies
      run: npm install

    - name: Deploy with AWS SAM
      run: |
        sam build
        sam deploy --no-confirm-changeset --capabilities CAPABILITY_IAM
